const languageData = {
    'zh-CN': {
        nav1: '序章',
        nav2: '纹样',
        nav3: '色彩',
        nav4: '形制',
        langButton: '中文',
        Minnan: '闽南布袋木偶戏',
        Minnantext1: '闽南布袋木偶戏是福建木偶戏代表剧种之一，承载着丰富的历史文化内涵。它以闽南傀儡调作为主要音乐唱腔，吸收了梨园戏和南音的部分曲牌；并在演出中融入当地的历史文化与民俗风情，赋予了戏剧生活气息；以精湛的雕刻技艺搭配传统戏剧服饰，使其成为福建戏剧之瑰宝。',
        Minnantext2: ' 本次展出的内容分为三个部分：纹饰戏语——《女中魁》服饰纹样；锦色戏韵——《李东假巡案》服饰色彩；偶影衣形——《大名府》服装造型。 ',
        font1: '关于我们',
        font2: '帮助中心',
        font3: '教育资源',
        font4: '© Minnan Puppet 2024, 版权所有',
        weishi1: '纹饰戏语',
        weishi2: '《李东假巡案》服饰纹样',
        weishi3: '《李东假巡案》',
        weishi4: '《李东假巡案》讲述了明朝天启年间，李东“以假乱真”，代替真巡按李彦彬将贪赃枉法的苏州',
        weishi5: ' 知府张春、总督方玉壁绳之以法的故事。',
        weishi6: '开始探索',
        jinse1: '锦色戏韵',
        jinse2: '《女中魁》服饰色彩',
        jinse3: '《女中魁》讲述了满娇容与其丈夫进京赶考，途中遇海盗，满娇容为护夫坠海后，与丈夫走散，',
        jinse4: '为寻找丈夫，女扮男装，历经困难，成为武状元为朝廷效力，并凭借自己的毅力与智慧，与丈夫',
        jinse5: '团聚，也获得皇帝的赏识，授予“女中魁”的称号。',
        jinse6: '《女中魁》',
        jinse7: '开始探索',
        ouying1: '偶影衣形',
        ouying2: '《大名府》服饰色彩',
        ouying3: '《大名府》',
        ouying4: '《大名府》讲述了宋元时期，梁山的英雄好汉为了搭救义士卢俊义，在元宵节化妆成各种杂耍',
        ouying5: '艺人，捉弄了大名府的城门官和衙役一番后，混入城内救人的故事。',
        ouying6: '开始探索',
        tansuo1: '探索木偶世界',
        tansuo2: '跟随我们一起，了解更多布袋木偶戏艺术',
        tansuo3: '历史发展',
        tansuo4: '经典赏析',
        tansuo5: '演出活动',
        zhoubian1: '周边产品',
        zhoubian2: '如果您喜欢我们的周边设计请随时与我们联系。',
        wenyang11: '鱼鳞纹',
        wenyang12: '鱼鳞纹常用于表现武将、战士等角色的服饰，象征着他们强大的战斗力和保护他人的能力。',
        wenyang21: '交枝牡丹纹',
        wenyang22: '盛开的牡丹象征繁花似锦，富贵吉祥。',
        wenyang31: '菊花组合纹',
        wenyang32: '象征高洁、坚韧的品格。',
        wenyang41: '宝相回纹',
        wenyang42: '宝相花象征富贵吉祥，回纹象征永恒和连续，两者结合传达了富贵长久、好运连绵的美好愿望。',
        wenyang51: '坐龙纹',
        wenyang52: '象征至高无上的皇权和威严，寓意着统治者的权力和神圣不可侵犯的地位。',
        wenyang61: '菊花卷草纹',
        wenyang62: '象征着坚韧不拔和高洁的品格',
        wenyang71: '全卧水纹',
        wenyang72: '象征着柔和和宁静的力量感。',
        wenyang81: '牡丹团花纹',
        wenyang82: '象征高贵典雅、富丽堂皇。',
        wenyang91: '如意回纹',
        wenyang92: '象征着和谐与幸福的生活状态。',
        about1: '致点开网页的你：',
        about2: '作为地地道道的福建人，我希望将我身边优秀的传统文化传递给更多的人，闽南布袋木偶戏作为福建戏剧的瑰宝， 陪伴了一代又一代人的成长。木偶在升级，演员在换新，观众在更迭，但不变的是刻在福建人心中的“看戏情怀”； 今天，我以这样的形式为大家展现了闽南布袋木偶戏的很小一部分，希望您能喜欢；未来，也将会上线更多内容； 让我们一起期待。',
        lishi11: ' 学界对于南派布袋木偶戏的起源变革尚无明确定论，但学界内存在两种观点：',
        lishi12: '  （一）以白勇华、洪世键为代表的一派认为南派布袋木偶戏产生于东晋时期，流行于宋代，盛行于清代。（二）是以叶明生为代表的一派认为南派布袋木偶戏产生于南宋时期，在明代流行，盛于清代。两个派别对于南派布袋木偶戏的起源有所分歧，但对其盛行时期的判断是一致的。',
        lishi21: ' 东晋',
        lishi22: ' 《拾遗记》中所记录的："南陲之南，有扶娄之国，其人善机巧变化……或于掌中备百戏之乐，宛转屈曲于指间。人形或长数分，或复数寸，神怪倏忽，玄丽于时……"',
        lishi31: ' 五 代',
        lishi32: ' 五代晋江人谭峭所著《化书·海鱼》载:“观傀儡之假而不自疑.......”',
        lishi41: ' 唐·敦煌莫高窟第31窟壁画局部图',
        lishi42: ' 唐代',
        lishi51: ' 宋·《蕉石婴戏图》',
        lishi52: ' 宋代',
        lishi61: ' 南 宋',
        lishi62: '  兴化人刘克庄(1187-1269)在其所作诗歌《己未元日》中说到:“久向优场脱戏衫，亦无布袋杖头担。”',
        lishi71: ' 明 代',
        lishi72: ' 《永春县志》卷十八《文化志) 载:“明天启年间，永春有两台木偶戏: 一是太平村李顺父子的布袋木偶;一是卿园村张森兄弟的提线木偶。”',
        lishi81: '  清 代',
        lishi82: '《晋江县志》卷之七十二《风俗志》载:“木头戏，俗名傀儡。近复有掌中弄巧，俗名布袋戏演唱一场各成音节。”',
        yanchu1: '关注公众号，了解最新演出活动资讯：',

        secai1: '闽南布袋木偶戏服饰在配色上会根据戏剧内容的变化而选择不一样的颜色搭配，但在整体用色规律上有着极其鲜明的特点，即使用对比色和邻近色作为主要的色彩组合方式，且利用相邻色彩间明度和纯度的差异性，产生波动变化，避免单一色彩所产生的视觉疲劳。在邻近色主色调基础上，运用互补色进行点缀装饰丰富视觉效果。除此之外，还通过色彩的明暗对比、纯度对比、冷暖对比以及面积对比手法，体现出色彩与色彩之间的协调与制衡关系，在视觉上进一步阐释戏剧所需要的情感表达。',
        ou1: '偶手',
        ou2: '偶帽',
        ou3: '偶脸',
        ou4: '偶衣',
        ou5: '偶身',

    },
    'en-US': {
        nav1: 'Prologue',
        nav2: 'Pattern',
        nav3: 'Color',
        nav4: 'Costume',
        langButton: 'English',
        Minnan: ' Minnan Glove Puppetry',
        Minnantext1: 'Minnan Glove Puppetry is one of the representative puppetry in Fujian, carrying rich historical and cultural connotations. It uses Minnan Glove Puppetry tune as the main musical singing style, absorbs some tunes of Liyuan Opera and Nanyin, and integrates local historical culture and folk customs into the performance, giving the drama a breath of life; exquisite carving skills and traditional drama costumes make it a treasure of Fujian drama.',
        Minnantext2: 'The contents of this exhibition are divided into three parts: Pattern--clothing patterns in "Nv Zhong Kui"; Color -- clothing colors in "Li Dong Jia Xun An "; and -Costume-- clothing styles in "Da Ming Fu".',
        font1: 'About Us',
        font2: 'Q&A',
        font3: 'Resources',
        font4: '© Minnan Puppet 2024, all rights reserved',
        weishi1: 'Pattern',
        weishi2: 'clothing patterns in "Li Dong Jia Xun An "',
        weishi3: 'Li Dong Jia Xun An',
        weishi4: '"Li Dong Jia Xun An " tells the story of how Li Dong, during the Tianqi period of the Ming Dynasty, replaced the real inspector Li Yanbin by "making a fake to be real" and brought the corrupt Suzhou prefect Zhang Chun and Governor Fang Yubi to justice.',
        weishi6: 'Exploring',
        jinse1: 'Color',
        jinse2: 'clothing colors in"Nv Zhong Kui"',
        jinse3: '"Nv Zhong Kui"tells the story of Man Jiaorong and her husband who went to Beijing for an imperial examination. On the way, they encountered pirates. Man Jiaorong fell into the sea while trying to protect her husband and was separated from her husband. ',
        jinse4: 'To find her husband, she disguised herself as a man and overcame many difficulties. She became the top military scholar and served the court',
        jinse5: 'With her perseverance and wisdom, she was reunited with her husband and was appreciated by the emperor, who awarded her the title of "The Female Champion"',
        jinse6: 'Nv Zhong Kui',
        jinse7: 'Exploring',
        ouying1: 'Costume',
        ouying2: 'clothing styles in "Da Ming Fu"',
        ouying3: 'Da Ming Fu',
        ouying4: '"Damingfu" tells the story of the Liangshan heroes in the Song and Yuan dynasties who dressed up as various jugglers during the Lantern Festival in order to rescue the righteous man Lu Junyi. ',
        ouying5: 'They played a trick on the city gate officials and yamen runners of Damingfu and then sneaked into the city to save people',
        ouying6: 'Exploring',
        tansuo1: 'Explore the world of puppets',
        tansuo2: 'Follow us to learn more about the art of Glove Puppetry',
        tansuo3: 'History',
        tansuo4: 'Performances',
        tansuo5: 'Events',
        zhoubian1: 'Peripheral products',
        zhoubian2: 'If you like our peripheral design, please feel free to contact us.',
        wenyang11: 'Fish-scale pattern',
        wenyang12: ' The fish scale pattern symbolizes their strong fighting power and ability to protect others.',
        wenyang22: ' The peony in full bloom is a symbol of prosperity and auspiciousness.',
        wenyang31: 'Chrysanthemum combination pattern',
        wenyang32: 'A symbol of noble, tough character.',
        wenyang41: 'Treasure phase back grain',
        wenyang42: 'The flower symbolizes wealth and auspiciousness, and the thread symbolizes eternity and continuity. The combination of the two conveys the good wish of wealth for a long time and good luck.',
        wenyang51: 'Sitting dragon pattern',
        wenyang52: 'It symbolizes the supreme imperial power and majesty, and implies the power and sacred and inviolable status of the ruler.',
        wenyang61: 'Chrysanthemum roll grass pattern',
        wenyang62: 'A symbol of perseverance and noble character',
        wenyang71: 'Full horizontal water pattern',
        wenyang72: 'It symbolizes a sense of gentle and serene power.',
        wenyang81: 'Peony pattern',
        wenyang82: 'Symbolizing nobility, elegance and grandeur.',
        wenyang91: 'Ruyi Huiwen',
        wenyang92: 'It symbolizes a harmonious and happy life.',
        about1: 'To everyone:',
        about2: 'As a true Fujianese, I hope to pass on the excellent traditional culture around me to more people. Minnan Bagua Opera, a treasure of Fujian opera, has accompanied the growth of generations of people. The puppets are being upgraded, the actors are being replaced, and the audience is changing, but what remains unchanged is the "theater-going sentiment" deeply engraved in the hearts of Fujianese people. Today, I am presenting a small part of Minnan Bagua Opera in this form, hoping that you will like it. In the future, we will also launch more content. Let’s look forward to it together.',
        lishi11: ' There is no clear conclusion in the academic community on the origin and evolution of Southern School of Puppetry, but there are two views in the academic community:',
        lishi12: '  (1) One faction, represented by Bai Yonghua and Hong Shijian, believes that the Southern School of glove puppetry originated in the Eastern Jin Dynasty, was popular in the Song Dynasty, and prevailed in the Qing Dynasty. (2) The school represented by Ye Mingsheng believes that the puppetry of the Southern School of cloth bags originated in the Southern Song Dynasty, became popular in the Ming Dynasty and flourished in the Qing Dynasty. The two factions differ on the origins of the Southern School of glove puppetry, but agree on the period of its popularity.',
        lishi21: ' The Eastern Jin Dynasty (917-907)',
        lishi22: ' Recorded in "Shiyiji": "South of the southern border, there is a country called Fulou, where people are good at making clever changes... Some of them prepare various kinds of music in their palms, twisting and turning between their fingers. The human figures are several centimeters long, or several inches long, and the gods and monsters appear suddenly, mysterious and beautiful at the time..." ',
        lishi31: ' The fifth generation',
        lishi32: '  Tan Qiao, a native of Jinjiang during the Five Dynasties, wrote in the book Huashu·Haiyu: "Looking at the puppets, I don’t doubt myself... "',
        lishi41: ' Tang Dunhuang Mogao Grottoes No. 31 cave fresco partial picture',
        lishi42: ' Tang Dynasty',
        lishi51: 'Song · "Jiao Shi Baby Play"',
        lishi52: ' Song Dynasty',
        lishi61: ' The Southern Song Dynasty',
        lishi62: 'Liu Kezhuang (1187-1269), a native of Xinghua, wrote in his poem "Jiwei New Year’s Day": "I have been taking off my clothes for a long time, and I have no cloth bag or stick to carry',
        lishi71: ' Ming Dynasty',
        lishi72: ' Volume 18 of the Yongchun County Annals (Cultural Annals) states: “During the reign of Emperor Tianqi of the Ming Dynasty, there were two puppet shows in Yongchun: one was the glove puppet show by Li Shun and his son from Taiping Village, and the other was the string puppet show by Zhang Sen and his brother from Qingyuan Village.',
        lishi81: '  Qing Dynasty',
        lishi82: 'Volume 72 of Jinjiang County Annals, Customs, states: "Wooden puppetry is commonly known as puppetry. Recently, there is also hand puppetry, commonly known as glove puppetry, in which each performance is a syllable. ',
        yanchu1: 'Follow the official account to learn about the latest performances and events:',
        secai1: 'The color matching of the costumes of the Minnan Glove Puppetry will be different according to the changes in the content of the drama, but the overall color usage has extremely distinct characteristics, that is, using contrasting colors and adjacent colors as the main color combination, and using the differences in brightness and purity between adjacent colors to produce fluctuations and avoid visual fatigue caused by a single color. On the basis of the main color of adjacent colors, complementary colors are used for embellishment and decoration to enrich the visual effect. In addition, the coordination and balance between colors are reflected through the contrast of light and dark, purity, cold and warm, and area, which further explains the emotional expression required by the drama visually.',
        ou1: 'Puppet hand',
        ou2: 'Hat',
        ou3: 'Puppet face',
        ou4: 'Puppet clothes',
        ou5: 'Puppet body',
    }
}

let currentLang = 'zh-CN'

function switchLanguage() {
    currentLang = currentLang === 'zh-CN' ? 'en-US' : 'zh-CN'
    updateContent()
    localStorage.setItem('language', currentLang)
}

function updateContent() {
    document.querySelectorAll('[data-lang]').forEach(element => {
        const key = element.getAttribute('data-lang')
        if (key === 'title') {
            document.title = languageData[currentLang][key]
        } else {
            element.textContent = languageData[currentLang][key]
        }
    })
}

document.getElementById('langToggle').addEventListener('click', switchLanguage)

// 初始化语言
const savedLang = localStorage.getItem('language')
if (savedLang) {
    currentLang = savedLang
    updateContent()
}